with location as(
    select * from {{source('FIVETRAN_INTERVIEW_DB','COVID_19_INDONESIA_PRAJAKTA_MARJE')}}
),

final as (
select TOTAL_RECOVERED,TOTAL_ACTIVE_CASES,LOCATION,COUNTRY
,TOTAL_CITIES,TOTAL_URBAN_VILLAGES,LOCATION_LEVEL,DATE from LOCATION)

select * from final