version: 2

sources:
  - name: FIVETRAN_INTERVIEW_DB
  - description: COVID19 dataset
  - database: FIVETRAN_INTERVIEW_DB
  - schema: GOOGLE_SHEETS
    tables:
      - name: COVID_19_INDONESIA_PRAJAKTA_MARJE
      -description: COVID19 dataset for prajatkamarje